import { DeviceSelection } from "./device-selection";
import "./globals.css";
import { TooltipProvider } from "@/components/plate-ui/tooltip";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { Raleway } from "next/font/google";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <DeviceSelection>
          <TooltipProvider
            disableHoverableContent
            delayDuration={500}
            skipDelayDuration={0}
          >
            {children}
          </TooltipProvider>
          <Toaster richColors />
        </DeviceSelection>
      </body>
    </html>
  );
}
