import { getServerAuthSession } from "./api/auth/[...nextauth]/auth-options";
import { DeviceSelection } from "./device-selection";
import "./globals.css";
import { QueryProvider } from "./query-provider";
import SessionProviderClientComponent from "./session-provider";
import { TooltipProvider } from "@/components/plate-ui/tooltip";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { Raleway } from "next/font/google";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerAuthSession();
  return (
    <html lang="en">
      <body className={raleway.className}>
        <SessionProviderClientComponent session={session}>
          <QueryProvider>
            <DeviceSelection>
              <TooltipProvider
                disableHoverableContent
                delayDuration={500}
                skipDelayDuration={0}
              >
                {children}
              </TooltipProvider>
              <Toaster richColors />
            </DeviceSelection>
          </QueryProvider>
        </SessionProviderClientComponent>
      </body>
    </html>
  );
}
