import "../../globals.css";
import { getServerAuthSession } from "@/app/api/auth/[...nextauth]/auth-options";
import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import { redirect } from "next/navigation";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerAuthSession();
  if (session) {
    redirect("/dashboard");
  }
  return (
    <main className="grid h-full min-h-[calc(100vh-80px)] grid-cols-2 items-center justify-center md:flex-row">
      <div className="hidden h-full w-full bg-black md:block"></div>

      {children}
    </main>
  );
}
